version: '3'

services:
  devweek_webapp:
    image: luizcarlosfaria/devweek_webapp:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports: 
      - "80:80"
    deploy:
      placement:
        constraints: 
          - node.labels.appenv == prd
      

  devweek_worker:
    image: luizcarlosfaria/devweek_worker:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 600s
      placement:
        constraints: 
          - node.labels.appenv == prd


  rabbitmq:
    ports: 
      - "20202:15672"
    deploy:
      placement:
        constraints: 
          - node.labels.appenv == prd

  s3:
    ports: 
      - "20203:9000"
    deploy:
      placement:
        constraints: 
          - node.labels.appenv == prd

  redis:
    ports:
      - "20204:6379"
    deploy:
      placement:
        constraints: 
          - node.labels.appenv == prd
