version: '3.4'

services:
  devweek_webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  rabbitmq:
    ports:
      - "15672"

  s3:
    ports:
      - "9000"

  redis:
    ports:
      - "6379"

  mongodb:
    ports:
      - "27017"
